#!/bin/sh
# Install a C compiler shim into the active virtualenv, backed by zig.
#
# Purpose: torch's Triton kernels and any C extension shell out to `cc` at runtime. Where build-essential cannot be
#          installed (no root), `pip install ziglang` provides a compiler that works, and this puts it on PATH under
#          the names those callers look for.
# Input:   $1, or $VIRTUAL_ENV, or ./.venv -- the virtualenv to install into
# Output:  <venv>/bin/cc and <venv>/bin/gcc
#
# Run once per machine after creating the virtualenv. Safe to re-run.
set -eu

venv=${1:-${VIRTUAL_ENV:-.venv}}
if [ ! -x "$venv/bin/python" ]; then
	echo "no virtualenv at $venv (expected $venv/bin/python)" >&2
	exit 1
fi

"$venv/bin/python" -m ziglang version >/dev/null 2>&1 || "$venv/bin/python" -m pip install ziglang

cat > "$venv/bin/cc" <<'SHIM'
#!/bin/sh
# A C compiler for this virtualenv, backed by zig. Generated by tools/repo/install_cc_shim.sh.
#
# zig's linker does not understand GNU's `-l:exactfile.so` form, and Triton links libcuda that way on WSL, so those
# arguments are rewritten to the absolute path of the file they name before zig sees them. The interpreter is found
# next to this script so the shim keeps working if the checkout moves.
set -eu

dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
libdirs="/usr/lib/wsl/lib /usr/lib/x86_64-linux-gnu /usr/lib /lib"
for arg in "$@"; do
	case $arg in
	-L*) libdirs="$libdirs ${arg#-L}" ;;
	esac
done

count=$#
while [ "$count" -gt 0 ]; do
	arg=$1
	shift
	case $arg in
	-l:*)
		name=${arg#-l:}
		for d in $libdirs; do
			if [ -f "$d/$name" ]; then
				arg=$d/$name
				break
			fi
		done
		;;
	esac
	set -- "$@" "$arg"
	count=$((count - 1))
done

exec "$dir/python" -m ziglang cc "$@"
SHIM

chmod +x "$venv/bin/cc"
cp "$venv/bin/cc" "$venv/bin/gcc"
echo "installed $venv/bin/cc and $venv/bin/gcc (zig $("$venv/bin/python" -m ziglang version))"
