"""Render the field-by-field reference in yug.md and vedant.md from their JSON contracts.

Run: uv run python tools/repo/render_field_reference.py

The markdown is the readable document and the JSON is the contract, so the two drift the moment anyone edits one by
hand. This regenerates the reference section from the JSON, between fixed markers, so a field can only be described in
one place. Re-run it after changing either contract.
"""

from __future__ import annotations

import json
from pathlib import Path

START = "<!-- FIELD REFERENCE: generated by tools/repo/render_field_reference.py -- do not edit by hand -->"
END = "<!-- END FIELD REFERENCE -->"


def table(rows: list[tuple[str, str]], head: tuple[str, str] = ("field", "what it is")) -> str:
    """A two-column markdown table with pipes escaped.

    Input:  (name, description) rows, the header pair
    Output: markdown
    """
    out = [f"| {head[0]} | {head[1]} |", "|---|---|"]
    out += [f"| `{n}` | {str(v).replace('|', '\\|')} |" for n, v in rows]
    return "\n".join(out)


def flatten(prefix: str, value, rows: list[tuple[str, str]]) -> None:
    """Walk a nested contract into (path, description) rows."""
    if isinstance(value, dict):
        for k, v in value.items():
            flatten(f"{prefix}.{k}" if prefix else k, v, rows)
    elif isinstance(value, list):
        rows.append((prefix, "; ".join(str(x) for x in value) if all(not isinstance(x, (dict, list)) for x in value)
                     else f"{len(value)} entries — see the JSON"))
    else:
        rows.append((prefix, value))


def render_yug(d: dict) -> str:
    parts = ["## Field reference\n",
             "*Generated from [yug.json](yug.json). Every field you send or emit, with its meaning and the mistake it "
             "invites.*\n"]
    for m in d["messages"]:
        rows: list[tuple[str, str]] = []
        flatten("", m["fields"], rows)
        parts.append(f"\n### Message kind {m['kind']} — `{m['name']}`\n")
        parts.append(f"**Available at:** {m['available_at']} · **Required:** {m['required']}\n")
        parts.append(f"{m['note']}\n" if m.get("note") else "")
        parts.append(table(rows))
    for name, key in (("Detection verdicts", "verdicts"), ):
        parts.append(f"\n### Output — {name}\n")
        for v in d["outputs"][key]:
            parts.append(f"\n**`stage = {v['stage']}`** — emitted at {v['emitted_at']}\n")
            parts.append(table([(f, "") for f in v["fields"]], ("field", "")).replace("|  |", "| see dev.json |"))
            if v.get("note"):
                parts.append(f"\n> {v['note']}\n")
    for key, title in (("anticipation", "Output — anticipation"), ("incidents", "Output — incidents")):
        rows = []
        flatten("", d["outputs"][key], rows)
        parts.append(f"\n### {title}\n")
        parts.append(table(rows))
    for key, title in (("alert_emission", "Alert emission"), ("state_limits", "State limits"),
                       ("throughput", "Throughput"), ("ordering", "Ordering and batching"),
                       ("timing_and_availability", "Timing and availability — exact definitions"),
                       ("who_consumes_what", "Which block consumes which message"),
                       ("required_means", "What 'required' means"),
                       ("statistics_you_must_report", "Statistics you must report"),
                       ("how_to_calculate", "How to calculate every statistic")):
        rows = []
        flatten("", d[key], rows)
        parts.append(f"\n### {title}\n")
        parts.append(table(rows))
    return "\n".join(parts)


def render_vedant(d: dict) -> str:
    parts = ["## Field reference\n",
             "*Generated from [vedant.json](vedant.json). Every column you read and every field you emit.*\n"]
    rows = []
    flatten("", d["input"]["columns"], rows)
    parts.append("\n### Input — `event_latents.parquet`\n")
    parts.append(table(rows))
    parts.append("\n**Warnings on this input**\n")
    parts.append("\n".join(f"* {w}" for w in d["input"]["warnings"]))
    for key, title in (("target_definitions", "Target definitions"), ("must_emit", "What you must emit"),
                       ("acceptance_criteria", "Acceptance criteria"), ("settled_by_measurement", "Settled by measurement"),
                       ("traps", "Traps"),
                       ("timing_and_availability", "Timing and availability — exact definitions"),
                       ("statistics_you_must_report", "Statistics you must report"),
                       ("how_to_calculate", "How to calculate every statistic")):
        rows = []
        flatten("", d[key], rows)
        parts.append(f"\n### {title}\n")
        parts.append(table(rows))
    return "\n".join(parts)


def splice(path: Path, body: str) -> None:
    """Replace the generated block in a markdown file, or append it if absent."""
    text = path.read_text()
    block = f"{START}\n\n{body}\n\n{END}"
    if START in text and END in text:
        head, rest = text.split(START, 1)
        text = head + block + rest.split(END, 1)[1]
    else:
        text = text.rstrip() + "\n\n---\n\n" + block + "\n"
    path.write_text(text)


def main() -> int:
    docs = Path("docs")
    splice(docs / "yug.md", render_yug(json.loads((docs / "yug.json").read_text())))
    splice(docs / "vedant.md", render_vedant(json.loads((docs / "vedant.json").read_text())))
    print("field reference rendered into docs/yug.md and docs/vedant.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
